messages:
  enabled_sneaking: Enabled automatic sneaking for %s
  disabled_sneaking: Disabled automatic sneaking for %s
  cooldown: Sneaking is disabled for another %s seconds

limits:
 cooldown: 0
 duration: 0