name: Sneaky
main: com.comphenix.sneaky.SneakyPlugin
version: 1.0.2-SNAPSHOT
description: A simple plugin that allows players to toggle automatic sneaking.
website: http://www.comphenix.net/Sneaky
dev-url: http://dev.bukkit.org/server-mods/sneaky/

depend: [ProtocolLib]
softdepend: [Vault]

permissions:
  sneaky.*:
    description: Gives access to everything.
    children:
      sneaky.sneak.self: true
      sneaky.sneak.other: true
  sneaky.sneak.*:
    description: Gives full access to the toggle command.
    children:
      sneaky.sneak.self: true
      sneaky.sneak.other: true
  sneaky.sneak.self:
    description: Toggle automatic sneaking of your own player.
    default: op
  sneaky.sneak.other:
    description: Toggle automatic sneaking of other players.
    default: op
  sneaky.hide.autosneak:
    description: Whether or not to hide all automatic sneaking for this player.
    default: false
  sneaky.exempt:
    description: If set, the player is not bound by any cooldown or duration limit.
    default: op

commands:
   sneak:
      description: Toggle the automatic sneaking of a given player.
      permission: sneaky.sneak.self
      aliases: [sneakysneak, sneaky_sneak]
      usage: /<command> [player] [on|off]
      