name: Sneaky
main: com.comphenix.sneaky.SneakyPlugin
version: 1.0.0
description: A simple plugin that allows players to toggle automatic sneaking.

depend: [ProtocolLib]

permissions:
  sneaky.*:
    description: Gives access to everything.
    children:
      sneaky.sneak.self: true
      sneaky.sneak.other: true
  sneaky.sneak.*:
    description: Gives full access to the toggle command.
    children:
      sneaky.sneak.self: true
      sneaky.sneak.other: true
  sneaky.sneak.self:
    description: Toggle automatic sneaking of your own player.
  sneaky.sneak.other:
    description: Toggle automatic sneaking of other players.
  sneaky.hide.autosneak:
    description: Whether or not to hide all automatic sneaking for this player.
  sneaky.exempt:
    description: If set, the player is not bound by any cooldown or duration limit.

commands:
   sneak:
      description: Toggle the automatic sneaking of a given player.
      permission: sneaky.sneak.self
      usage: /<command> [player]
      