package com.comphenix.sneaky.cooldown;

import java.util.EventObject;

import org.bukkit.entity.Player;

public class CooldownExpiredEvent extends EventObject {
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 4667215597341788588L;
	
	private Player player;
	
	public CooldownExpiredEvent(Object source, Player player) {
		super(source);
		this.player = player;
	}

	/**
	 * Retrieve the player whose cooldown has expired.
	 * @return Player affected by a expired cooldown.
	 */
	public Player getPlayer() {
		return player;
	}
}
