package com.comphenix.sneaky.cooldown;

import java.util.EventObject;

import org.bukkit.entity.Player;

/**
 * Represents a cooldown expired event.
 * 
 * @author Kristian
 */
public class CooldownExpiredEvent extends EventObject {
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 4667215597341788588L;
	
	private Player player;
	
	/**
	 * Construct a cooldown expired event with the event source and target player.
	 * @param source - the object that determined the cooldown to be expired.
	 * @param player - the player whose cooldown has expired.
	 */
	public CooldownExpiredEvent(Object source, Player player) {
		super(source);
		this.player = player;
	}

	/**
	 * Retrieve the player whose cooldown has expired.
	 * @return Player affected by a expired cooldown.
	 */
	public Player getPlayer() {
		return player;
	}
}
