package com.comphenix.sneaky.cooldown;

/*
 *  Sneaky - A simple plugin that allows players to toggle automatic sneaking.
 *  Copyright (C) 2013 Kristian S. Stangeland
 *
 *  This program is free software; you can redistribute it and/or modify it under the terms of the 
 *  GNU General Public License as published by the Free Software Foundation; either version 2 of 
 *  the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 *  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program; 
 *  if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 
 *  02111-1307 USA
 */

import java.util.EventObject;

import org.bukkit.entity.Player;

/**
 * Represents a cooldown change event.
 * 
 * @author Kristian
 */
public class CooldownChangedEvent extends EventObject {
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = -1375858549864271307L;
	
	private final Player player;
	private final Long fromValue;
	private final Long toValue;

	public CooldownChangedEvent(Object source, Player player, Long fromValue, Long toValue) {
		super(source);
		
		this.player = player;
		this.fromValue = fromValue;
		this.toValue = toValue;
	}

	public Player getPlayer() {
		return player;
	}

	/**
	 * Retrieve the original cooldown value in milliseconds since 1970.
	 * @return Cooldown value, or NULL if not set.
	 */
	public Long getFromValue() {
		return fromValue;
	}

	/**
	 * Retrieve the new cooldown value in milliseconds since 1970.
	 * @return New cooldown value, or NULL if removed.
	 */
	public Long getToValue() {
		return toValue;
	}
}
