package com.comphenix.sneaky.cooldown;

import java.util.EventObject;

import org.bukkit.entity.Player;

public class ExpiredEvent extends EventObject {
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 4667215597341788588L;
	
	private Player player;
	
	public ExpiredEvent(Object source, Player player) {
		super(source);
		this.player = player;
	}

	public Player getPlayer() {
		return player;
	}
}
